import { type User as FirebaseUser } from 'firebase/auth';
import { Timestamp } from 'firebase/firestore';

/**
 * Extended User interface combining Firebase Auth user with custom user data
 * Stored in Firestore collection: users/{uid}
 */
export interface User {
  /** Firebase Authentication UID */
  uid: string;
  /** User email address */
  email: string;
  /** User display name (can be null if not set) */
  displayName: string | null;
  /** User profile photo URL (can be null if not set) */
  photoURL: string | null;
  /** Account creation timestamp */
  createdAt: Timestamp;
  /** Last update timestamp */
  updatedAt: Timestamp;
}

/**
 * Bookmark interface representing a saved web page
 * Stored in Firestore collection: bookmarks/{bookmarkId}
 */
export interface Bookmark {
  /** Unique bookmark ID (auto-generated by Firestore) */
  id: string;
  /** User ID who owns this bookmark */
  userId: string;
  /** Page title */
  title: string;
  /** Page URL */
  url: string;
  /** Optional description or notes about the bookmark */
  description: string | null;
  /** Firebase Storage URL for the screenshot (null if not yet captured) */
  screenshotUrl: string | null;
  /** Firebase Storage path for the screenshot (used for deletion) */
  screenshotPath: string | null;
  /** Array of tag names associated with this bookmark */
  tags: string[];
  /** Bookmark creation timestamp */
  createdAt: Timestamp;
  /** Last update timestamp */
  updatedAt: Timestamp;
  /** Optional: Error message if screenshot capture failed */
  screenshotError?: string;
  /** Optional: Number of screenshot capture retry attempts */
  screenshotRetries?: number;
}

/**
 * Tag interface for bookmark categorization
 * Stored in Firestore collection: tags/{tagName}
 * Tags are automatically created and updated by Cloud Functions
 */
export interface Tag {
  /** Tag ID (same as tag name, used as document ID) */
  id: string;
  /** Tag name/label */
  name: string;
  /** Number of bookmarks using this tag */
  count: number;
  /** Timestamp of when this tag was last used */
  lastUsed: Timestamp;
}

/**
 * Filters for searching and filtering bookmarks
 * Used in bookmark list queries
 */
export interface BookmarkFilters {
  /** Search query (searches in title and description) */
  search?: string;
  /** Filter by multiple tags (array-contains-any query) */
  tags?: string[];
  /** Filter bookmarks created after this date */
  dateFrom?: Date | null;
  /** Filter bookmarks created before this date */
  dateTo?: Date | null;
  /** Number of bookmarks to fetch per page */
  limit?: number;
  /** Last document ID for cursor-based pagination */
  lastDoc?: string | null;
}

/**
 * Data required to create a new bookmark
 * Used when calling createBookmark Cloud Function
 */
export interface CreateBookmarkData {
  /** Page URL (required) */
  url: string;
  /** Page title (required) */
  title: string;
  /** Optional description */
  description?: string;
  /** Optional array of tags */
  tags?: string[];
}

/**
 * Data for updating an existing bookmark
 * Used when calling updateBookmark Cloud Function
 */
export interface UpdateBookmarkData {
  /** Updated title */
  title?: string;
  /** Updated description */
  description?: string;
  /** Updated tags array */
  tags?: string[];
}

/**
 * Response from getBookmarks Cloud Function
 * Includes bookmarks data and pagination info
 */
export interface BookmarksResponse {
  /** Array of bookmarks */
  data: Bookmark[];
  /** ID of the last document (for pagination) */
  lastDoc: string | null;
  /** Whether there are more bookmarks to fetch */
  hasMore: boolean;
}

/**
 * Authentication context type
 * Used by AuthContext provider
 */
export interface AuthContextType {
  /** Currently authenticated user (null if not logged in) */
  user: FirebaseUser | null;
  /** Loading state during authentication check */
  loading: boolean;
  /** Login function */
  login: (email: string, password: string) => Promise<void>;
  /** Register function */
  register: (email: string, password: string, displayName: string) => Promise<void>;
  /** Logout function */
  logout: () => Promise<void>;
  /** Password reset function */
  forgotPassword: (email: string) => Promise<void>;
}

/**
 * Form data for login
 */
export interface LoginFormData {
  email: string;
  password: string;
}

/**
 * Form data for registration
 */
export interface RegisterFormData {
  email: string;
  password: string;
  confirmPassword: string;
  displayName: string;
}

/**
 * Form data for forgot password
 */
export interface ForgotPasswordFormData {
  email: string;
}

/**
 * Generic API error response
 */
export interface ApiError {
  code: string;
  message: string;
}

/**
 * Toast notification type
 */
export type ToastType = 'success' | 'error' | 'info' | 'warning';

/**
 * Toast notification interface
 */
export interface Toast {
  id: string;
  type: ToastType;
  message: string;
  duration?: number;
}
